version: '2.2'
services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es02
    environment:
      - network.host=0.0.0.0
      - network.publish_host=10.128.0.5
      - discovery.zen.ping.unicast.hosts=10.128.0.4
        #      - network.host=_site_
      - node.name=es02
      - cluster.name=docker-cluster
        #      - discovery.seed_hosts=10.128.0.4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://10.128.0.5:9200
      ELASTICSEARCH_HOSTS: '["http://10.128.0.4:9200","http://10.128.0.5:9200"]'
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
