version: '2.2'

services:
  elastic02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: elastic02
    environment:
      - node.name=elastic02
      - network.host=0.0.0.0
      - network.publish_host=10.128.0.5
      - discovery.zen.ping.unicast.hosts=10.128.0.4
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=10.128.0.4,10.128.0.5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - "ELASTIC_PASSWORD=elastic"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true 
      - xpack.security.http.ssl.key=$CERTS_DIR/elastic02/elastic02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/elastic02/elastic02.crt
      - xpack.security.transport.ssl.enabled=true 
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/elastic02/elastic02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/elastic02/elastic02.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data02:
    driver: local
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
